DATASET:
  CHANNELS: 1
  FOLDS_COUNT: 5
  MEAN: 0.1307
  PATH: mnist
  STD: 0.3081
  TOTAL_CLASS_COUNT: 10
  PERCENTAGES: [10, 20, 30, 40, 50]
MODEL:
  LATENT_SIZE: 16
  Z_DISCRIMINATOR_CROSS_BATCH: False
NUM_WORKERS: 4
OUTPUT_DIR: results
TRAIN:
  DO_TRAINING: True
  BASE_LEARNING_RATE: 0.002
  BATCH_SIZE: 128
  EPOCH_COUNT: 80
INLIER_CLASSES: [2]
#INLIER_CLASSES: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
