DATASET:
  PERCENTAGES: [10, 20, 30, 40, 50]
MODEL:
  LATENT_SIZE: 2
  Z_DISCRIMINATOR_CROSS_BATCH: False
  INPUT_IMAGE_CHANNELS: 2
OUTPUT_DIR: results
TRAIN:
  BASE_LEARNING_RATE: 0.002
  BATCH_SIZE: 256
  EPOCH_COUNT: 80

